name: invite-on-label
description: Send invitation based on issue
author: Abishek P.Y
branding:
  icon: anchor
  color: green
inputs:
  organization:
    description: Name of the organization to which you would like to invite contributors.
    required: true
  label:
    description: Name of the label
    required: true
  repo-token:
    description: 'GitHub token for repo'
    required: true
  comment:
    description: A comment which will be posted on the issue.
    required: false
    default: Invitation sent for the GitHub Organisation. Welcome to the community
runs:
  using: node12
  main: dist/index.js
